### ISSUE TITLE
Didn't get any errors to php file

### ISSUE THREAD

**Issue by seshuvinay** [tomquist/Android-Error-Reporter#7]
I followed 4 steps given in the description. I also have a php file in my server. I didn't get any reports. Does it take time to get reports or does it get instantly?

**Comment by tomquist** [comment]
Did you set the meta-data `de.quist.app.errorreporter.reportOnFroyo` to true?

**Comment by seshuvinay** [comment]
no, I made it false. BTW I don't have my app in Froyo devices. My minSdkVersion is 14.

**Comment by seshuvinay** [comment]
And I got this in my logcat:
07-11 11:25:47.312: V/ExceptionReportService(3324): Got request to report error: Intent { act=de.quist.app.errorreporter.actionSendReport dat=custom://255526004 cmp=com.quackquack/de.quist.app.errorreporter.ExceptionReportService (has extras)

**Comment by seshuvinay** [comment]
Ok, thanks. It's working after making it true

**Comment by tomquist** [comment]
You have to set it to true. Otherwise exceptions don't get reported on froyo and above
